const Quotes=[
    {
        "1": "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.",
        "2": "The only way to do great work is to love what you do.",
        "3": "Success usually comes to those who are too busy to be looking for it.",
        "4": "Don’t be afraid to give up the good to go for the great.",
        "5": "Opportunities don't happen. You create them.",
        "6": "Success is not in what you have, but who you are.",
        "7": "The harder you work for something, the greater you’ll feel when you achieve it.",
        "8": "Dream bigger. Do bigger.",
        "9": "Don’t stop when you’re tired. Stop when you’re done.",
        "10": "The way to get started is to quit talking and begin doing.",
        "11": "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
        "12": "Don’t let yesterday take up too much of today.",
        "13": "You learn more from failure than from success. Don’t let it stop you. Failure builds character.",
        "14": "It’s not whether you get knocked down, it’s whether you get up.",
        "15": "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.",
        "16": "People who are crazy enough to think they can change the world, are the ones who do.",
        "17": "Failure will never overtake me if my determination to succeed is strong enough.",
        "18": "We may encounter many defeats but we must not be defeated.",
        "19": "Knowing is not enough; we must apply. Wishing is not enough; we must do.",
        "20": "Imagine your life is perfect in every respect; what would it look like?",
        "21": "We generate fears while we sit. We overcome them by action.",
        "22": "Whether you think you can or think you can’t, you’re right.",
        "23": "Security is mostly a superstition. Life is either a daring adventure or nothing.",
        "24": "The man who has confidence in himself gains the confidence of others.",
        "25": "The only limit to our realization of tomorrow will be our doubts of today.",
        "26": "Creativity is intelligence having fun.",
        "27": "What you lack in talent can be made up with desire, hustle, and giving 110% all the time.",
        "28": "Do what you can with all you have, wherever you are.",
        "29": "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.",
        "30": "Nothing in the world can take the place of persistence.",
        "31": "Knowing is not enough; we must apply. Wishing is not enough; we must do.",
        "32": "Success is not final; failure is not fatal: It is the courage to continue that counts.",
        "33": "Believe you can and you’re halfway there.",
        "34": "Act as if what you do makes a difference. It does.",
        "35": "You don’t have to be great to start, but you have to start to be great.",
        "36": "Don’t wait for opportunity. Create it.",
        "37": "Your limitation—it’s only your imagination.",
        "38": "Push yourself, because no one else is going to do it for you.",
        "39": "Great things never come from comfort zones.",
        "40": "Dream it. Wish it. Do it.",
        "41": "Success doesn’t just find you. You have to go out and get it.",
        "42": "The harder you work for something, the greater you’ll feel when you achieve it.",
        "43": "Dream bigger. Do bigger.",
        "44": "Don’t stop when you’re tired. Stop when you’re done.",
        "45": "Wake up with determination. Go to bed with satisfaction.",
        "46": "Do something today that your future self will thank you for.",
        "47": "Little things make big days.",
        "48": "It’s going to be hard, but hard does not mean impossible.",
        "49": "Don’t wait. The time will never be just right.",
        "50": "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle."
      }
      
   
]
export default Quotes;